import { GameType, GameLibraryItem } from '../types';

// Game Library — shared between SetupWizard and TournamentBuildRoundWizard
export const GAME_LIBRARY: GameLibraryItem[] = [
  {
    type: GameType.BANKER,
    name: "Banker",
    description: 'One player is "banker" each hole. Banker vs all other players with multipliers.',
    icon: "🏦",
    defaultUnitStake: 3,
    minPlayers: 2,
    maxPlayers: 8,
    config: { birdieMultiplier: 3, eagleMultiplier: 5, useHandicaps: true, handicapMode: 'relative' },
  },
  {
    type: GameType.BLOODY_BANKER,
    name: "Bloody Banker",
    description: 'One player is "banker" each hole. Banker vs all other players with multipliers.',
    icon: "🩸",
    defaultUnitStake: 3,
    minPlayers: 2,
    maxPlayers: 8,
    config: { birdieMultiplier: 3, eagleMultiplier: 5, useHandicaps: true, handicapMode: 'relative' },
  },
  {
    type: GameType.STOCKTON_6,
    name: "Stockton 6's",
    description: "2-player teams: 1-Ball & 2-Ball Nassau over 6-hole stretches with auto-presses and dots.",
    icon: "6️⃣",
    defaultUnitStake: 5,
    minPlayers: 4,
    maxPlayers: 4,
    config: { stockton6: { dotValue: 2 } },
  },
  {
    type: GameType.FBO,
    name: "FBO (Front/Back/Overall)",
    description: "Match play dots: 3 bets for Front 9, Back 9, and Overall 18.",
    icon: "🎱",
    defaultUnitStake: 10,
    minPlayers: 2,
    maxPlayers: 8,
    config: { fboPlayers: [], useHandicaps: true, fbo: { allowPresses: true } },
  },
  {
    type: GameType.SKINS,
    name: "Skins",
    description: "Lowest net score wins the skin. Ties carry over to next hole.",
    icon: "🎯",
    defaultUnitStake: 3,
    minPlayers: 2,
    maxPlayers: 8,
    config: { carryovers: true, useHandicaps: true, handicapMode: 'relative' },
  },
  {
    type: GameType.NASSAU,
    name: "Nassau",
    description: "Three separate bets: Front 9, Back 9, and Overall (2 players only).",
    icon: "🏌️",
    defaultUnitStake: 3,
    minPlayers: 2,
    maxPlayers: 2,
    config: { presses: false, useHandicaps: true, handicapMode: 'relative' },
  },
  {
    type: GameType.OPEN_BETTING,
    name: "Open Betting",
    description: "Manual side bets - track any wager between players.",
    icon: "💰",
    defaultUnitStake: 3,
    minPlayers: 2,
    maxPlayers: 8,
    config: { useHandicaps: false },
  },
  {
    type: GameType.WOLF,
    name: "Wolf",
    description: "Strategic 4-player game. Wolf picks partner after tee shots or goes solo for more points.",
    icon: "🐺",
    defaultUnitStake: 1,
    minPlayers: 4,
    maxPlayers: 4,
    config: { useHandicaps: true, handicapMode: 'relative', wolf: { teesFirst: true } },
  },
  {
    type: GameType.NINE_POINTS,
    name: "Nine Points",
    description: "9 points split each hole: 5-3-1 for 1st-2nd-3rd place based on net scores. Optional Home Run rule sweeps all 9 on a 2+ stroke win.",
    icon: "9️⃣",
    defaultUnitStake: 1,
    minPlayers: 3,
    maxPlayers: 3,
    config: { useHandicaps: true, handicapMode: 'relative', ninePoints: { homeRunEnabled: false } },
  },
  {
    type: GameType.SIXES,
    name: "6's or 3's",
    description: "2v2 match play: lowest ball wins each hole. Most holes won per stretch takes the bet.",
    icon: "🎲",
    defaultUnitStake: 10,
    minPlayers: 4,
    maxPlayers: 4,
    config: { useHandicaps: true, handicapMode: 'absolute', sixes: { useSecondBallTiebreaker: false, mode: 'sixes' } },
  },
  {
    type: GameType.TEAM_BANKER,
    name: "Team Banker",
    description: "2v2 team game: all players pick multipliers, team with best net score wins.",
    icon: "🏦👥",
    defaultUnitStake: 3,
    minPlayers: 4,
    maxPlayers: 4,
    config: { useHandicaps: true, handicapMode: 'relative', birdieMultiplier: 3, eagleMultiplier: 5, teamBanker: { mode: 'sixes', useSecondBallTiebreaker: false } },
  },
  {
    type: GameType.HAMMER,
    name: "Hammer",
    description: "Throw the hammer to double the pot. Team Hammer (2v2) or LR Hammer (per-hole teams).",
    icon: "🔨",
    defaultUnitStake: 5,
    minPlayers: 3,
    maxPlayers: 4,
    config: {
      hammer: { variant: 'team', segmentLength: 18, useSecondBallTiebreaker: false },
      birdieMultiplier: 1,
      eagleMultiplier: 1,
      useHandicaps: true,
      handicapMode: 'relative',
    },
  },
];

// Detailed game info for popovers
export const GAME_DETAILS: Record<string, { howItWorks: string; idealPlayers: string; examplePayout: string }> = {
  [GameType.BANKER]: { howItWorks: "Each hole, one player is designated the 'banker' and plays against everyone else. Players choose multipliers (1x-5x) before the hole. Birdies triple the payout, eagles quintuple it.", idealPlayers: "3-4 players", examplePayout: "$3 unit × 3x multiplier × birdie = $27 win" },
  [GameType.BLOODY_BANKER]: { howItWorks: "Same as Banker, but on holes 16-18, the player losing the most money is forced to be banker — adding extra pressure.", idealPlayers: "3-4 players", examplePayout: "$3 unit × forced banker on 18 = high-stakes finish" },
  [GameType.STOCKTON_6]: { howItWorks: "Teams of 2 play 1-Ball and 2-Ball Nassau across three 6-hole stretches. Includes dots (birdie, greenie) and auto-presses when 2-down.", idealPlayers: "Exactly 4 players", examplePayout: "$5 unit: ~$30-60 swing per stretch" },
  [GameType.FBO]: { howItWorks: "Each hole, lowest net score earns a 'dot.' Three bets run simultaneously: Front 9, Back 9, and Overall 18. Player with most dots in each segment wins.", idealPlayers: "2-8 players", examplePayout: "$10/segment: 5 dots vs 3 dots = $20 win" },
  [GameType.SKINS]: { howItWorks: "Lowest net score wins the 'skin' on each hole. If two or more players tie, the skin carries over to the next hole, building the pot.", idealPlayers: "3-4 players", examplePayout: "$3/skin: 3 carryovers = $12 skin" },
  [GameType.NASSAU]: { howItWorks: "Three separate match-play bets: Front 9, Back 9, and Overall 18. Each is an independent wager based on net scores.", idealPlayers: "Exactly 2 players", examplePayout: "$3/bet: max exposure $9" },
  [GameType.OPEN_BETTING]: { howItWorks: "Manually track any side bet between players — closest to pin, longest drive, or any custom wager you agree on.", idealPlayers: "Any group size", examplePayout: "Whatever you agree on!" },
  [GameType.WOLF]: { howItWorks: "Rotating 'Wolf' picks a partner after watching tee shots, or goes Lone Wolf for double points. Blind Lone Wolf (declared before anyone tees off) pays 3x.", idealPlayers: "Exactly 4 players", examplePayout: "$1/point: Lone Wolf win = $3/player" },
  [GameType.NINE_POINTS]: { howItWorks: "9 points split each hole among 3 players: 5 for best net, 3 for second, 1 for worst. At the end, points are compared and differences paid out. Optional Home Run rule: win a hole outright by 2+ net strokes to sweep all 9 points.", idealPlayers: "Exactly 3 players", examplePayout: "$1/point: 36-point target over 18" },
  [GameType.SIXES]: { howItWorks: "2v2 teams rotate every 6 holes (or every 3). Lowest ball wins each hole. Team winning the most holes in a stretch wins the bet.", idealPlayers: "Exactly 4 players", examplePayout: "$10/stretch: win 4 holes vs 2 = $20" },
  [GameType.TEAM_BANKER]: { howItWorks: "2v2 team version of Banker. All players choose multipliers. Team with the best combined net score wins, applying multipliers for payouts.", idealPlayers: "Exactly 4 players", examplePayout: "$3 unit: team multipliers amplify" },
  [GameType.HAMMER]: { howItWorks: "Each hole starts at the base bet. Either team can throw the Hammer to double the pot — the other team must accept or throw it back (doubling again). Lowest net ball wins; ties push and reset. Team Hammer = fixed 2v2 teams per segment. LR Hammer = pick teams each hole (2v2 with 4 players, or 2v1 with 3).", idealPlayers: "3-4 players", examplePayout: "$5 base + 2 throws = $20/player. Birdie 3x = $60/player." },
};
