project_id = "wvmpxjcghlgtitdhozlj"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-reset-email]
verify_jwt = false

[functions.generate-reset-link]
verify_jwt = false

[functions.search-course-perplexity]
verify_jwt = false
